# Generated by Django 5.2.1 on 2025-06-04 12:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_order_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='view_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
