# Generated by Django 5.2.1 on 2025-06-04 12:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_order_view_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='view_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
