# Generated by Django 5.2.1 on 2025-06-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_order_view_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='current_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Ocupada'), ('reserved', 'Reservada'), ('unavailable', 'No disponible')], default='available', max_length=20),
        ),
    ]
