# Generated by Django 5.2.1 on 2025-06-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_table_current_code_alter_table_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('preparing', 'En preparación'), ('delivered', 'Entregado'), ('paid', 'Pagado'), ('annulled', 'Anulado')], default='pending', max_length=20),
        ),
    ]
