# Generated by Django 5.2.1 on 2025-06-05 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_order_paid_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Monto total del pedido en el momento de la venta.', max_digits=10)),
                ('sale_timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró la venta.')),
                ('order', models.OneToOneField(help_text='El pedido al que corresponde esta venta.', on_delete=django.db.models.deletion.PROTECT, related_name='sale_record', to='management.order')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Usuario de personal que procesó esta venta.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Venta',
                'verbose_name_plural': 'Registros de Ventas',
                'ordering': ['-sale_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SaleItemRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Nombre del producto en el momento de la venta.', max_length=255)),
                ('product_price_at_sale', models.DecimalField(decimal_places=2, help_text='Precio del producto en el momento de la venta.', max_digits=10)),
                ('quantity', models.IntegerField(help_text='Cantidad vendida de este producto.')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal por este artículo (cantidad * precio en venta).', max_digits=10)),
                ('sale_record', models.ForeignKey(help_text='Registro de venta al que pertenece este artículo.', on_delete=django.db.models.deletion.CASCADE, related_name='items_sold', to='management.salerecord')),
            ],
            options={
                'verbose_name': 'Artículo Vendido',
                'verbose_name_plural': 'Artículos Vendidos',
            },
        ),
    ]
